### ISSUE TITLE
Release builds busted

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#70] opened 2016-10-11 21:09 UTC
It looks like something about the wrappers extensions.  Then generate a pile of linker errors at the moment.  Debug works.

**Comment by thomasvl** [comment] 2016-10-11 21:10
Linking SwiftProtobufTestSuite_iOS

```
Undefined symbols for architecture i386:
  "(extension in SwiftProtobuf):SwiftProtobuf.ProtobufWrapper.init (A.WrappedType.BaseType) -> A", referenced from:
      SwiftProtobufTestSuite_iOS.Test_Api.testInitializer () -> () in Test_Api.o
      SwiftProtobufTestSuite_iOS.Test_Conformance.(testRepeatedBoolWrapper () -> ()).(closure #1) in Test_Conformance.o
      SwiftProtobufTestSuite_iOS.Test_Conformance.(testRepeatedBoolWrapper () -> ()).(closure #2) in Test_Conformance.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.testDoubleValue () throws -> () in Test_Wrappers.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.testFloatValue () throws -> () in Test_Wrappers.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.(testStringValue () throws -> ()).(implicit closure #11) in Test_Wrappers.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.(testStringValue () throws -> ()).(implicit closure #13) in Test_Wrappers.o
      ...
  "protocol witness table for SwiftProtobuf.Google_Protobuf_BoolValue : SwiftProtobuf.ProtobufWrapper in SwiftProtobuf", referenced from:
      SwiftProtobufTestSuite_iOS.Test_Conformance.(testRepeatedBoolWrapper () -> ()).(closure #1) in Test_Conformance.o
      SwiftProtobufTestSuite_iOS.Test_Conformance.(testRepeatedBoolWrapper () -> ()).(closure #2) in Test_Conformance.o
  "protocol witness table for SwiftProtobuf.Google_Protobuf_FloatValue : SwiftProtobuf.ProtobufWrapper in SwiftProtobuf", referenced from:
      SwiftProtobufTestSuite_iOS.Test_Wrappers.testFloatValue () throws -> () in Test_Wrappers.o
  "protocol witness table for SwiftProtobuf.Google_Protobuf_DoubleValue : SwiftProtobuf.ProtobufWrapper in SwiftProtobuf", referenced from:
      SwiftProtobufTestSuite_iOS.Test_Wrappers.testDoubleValue () throws -> () in Test_Wrappers.o
  "protocol witness table for SwiftProtobuf.Google_Protobuf_StringValue : SwiftProtobuf.ProtobufWrapper in SwiftProtobuf", referenced from:
      SwiftProtobufTestSuite_iOS.Test_Api.testInitializer () -> () in Test_Api.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.(testStringValue () throws -> ()).(implicit closure #11) in Test_Wrappers.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.(testStringValue () throws -> ()).(implicit closure #13) in Test_Wrappers.o
      SwiftProtobufTestSuite_iOS.Test_Api.testInitializer () -> () in Test_Api.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.(testStringValue () throws -> ()).(implicit closure #11) in Test_Wrappers.o
      SwiftProtobufTestSuite_iOS.Test_Wrappers.(testStringValue () throws -> ()).(implicit closure #13) in Test_Wrappers.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thomasvl** [comment] 2016-10-11 21:19
repeats for both macOS and iOS release builds.

**Comment by allevato** [comment] 2016-10-11 21:21
At first glance, this looks like a potential compiler/linker bug to me, where it's possibly getting confused because we have external code (the test module) trying to call an initializer that's defined on an internal protocol, even though the initializer is re-declared public in the extension where the default is implemented.

One way to test it would be to move the `public init(_ value: WrappedType.BaseType)` impl into the individual wrapper extensions to see if that fixes the visibility issue.

Will investigate further.

**Comment by allevato** [comment] 2016-10-11 22:18
Confirmed: adding the initializer into the concrete wrapper type instead of the protocol extension fixes the issue. I'll have a PR shortly that copies the initializer into each of the concrete types; unfortunately this will create a small amount of duplication in the runtime library.

I'll see if I can isolate this into a small example that can be submitted as a Swift bug. My understanding is that one of two things should be happening here:

1. Designating a method as public on an extension of an internal protocol *should* be allowed and the linker should be able to see that method when resolving calls from externally linked code.
2. Designating a method as public on an extension of an internal protocol *should not* be allowed and the compiler should flag this as an error before it ever gets to the linker.

Presumably this only occurs on release builds due to stripping or optimization settings that reduce the visibility of certain symbols.

**Comment by thomasvl** [comment] 2016-10-12 00:34
Thanks.  Lets make sure we track (maybe make a label for them and open issues for tracking them) these sort things (that are possibly compiler bugs).  I'm a little worried about making sure we under stand them as if they are settings related, this could show up multiple times (the checked in project, CocoaPods generated projects, Swift package manager).

**Closed** 2016-10-12 14:27 UTC

**Comment by allevato** [comment] 2016-10-12 15:46
I've filed https://bugs.swift.org/browse/SR-2925 about this to see if what we were trying to do should be allowed.

**Comment by yoiang** [comment] 2018-09-08 04:00
@allevato can you clarify your temporary fix? I am running into what looks like a similar issue, when I reference one of my generated classes' (GTFS) initializers I am getting linking errors: 

```
Undefined symbols for architecture x86_64:
  "default argument 1 of (extension in SwiftProtobuf):SwiftProtobuf.Message.init(serializedData: Foundation.Data, extensions: SwiftProtobuf.ExtensionMap?, partial: Swift.Bool, options: SwiftProtobuf.BinaryDecodingOptions) throws -> A", referenced from:
      GTFSRealtimeKitTests.GTFSRealtimeBindingsTests.testGTFSRealtimeAPI_FeedMessage_decode() -> () in gtfs-realtime.pb.o
  "default argument 2 of (extension in SwiftProtobuf):SwiftProtobuf.Message.init(serializedData: Foundation.Data, extensions: SwiftProtobuf.ExtensionMap?, partial: Swift.Bool, options: SwiftProtobuf.BinaryDecodingOptions) throws -> A", referenced from:
      GTFSRealtimeKitTests.GTFSRealtimeBindingsTests.testGTFSRealtimeAPI_FeedMessage_decode() -> () in gtfs-realtime.pb.o
  "default argument 3 of (extension in SwiftProtobuf):SwiftProtobuf.Message.init(serializedData: Foundation.Data, extensions: SwiftProtobuf.ExtensionMap?, partial: Swift.Bool, options: SwiftProtobuf.BinaryDecodingOptions) throws -> A", referenced from:
      GTFSRealtimeKitTests.GTFSRealtimeBindingsTests.testGTFSRealtimeAPI_FeedMessage_decode() -> () in gtfs-realtime.pb.o
  "(extension in SwiftProtobuf):SwiftProtobuf.Message.init(serializedData: Foundation.Data, extensions: SwiftProtobuf.ExtensionMap?, partial: Swift.Bool, options: SwiftProtobuf.BinaryDecodingOptions) throws -> A", referenced from:
      GTFSRealtimeKitTests.GTFSRealtimeBindingsTests.testGTFSRealtimeAPI_FeedMessage_decode() -> () in gtfs-realtime.pb.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by allevato** [comment] 2018-09-10 15:22
The fix I describe above was solely internal to the runtime library, so it shouldn't be affecting any user code. The tl;dr is that I defined an internal protocol and a default implementation of a method in that protocol so I could share its implementation across all conformers. I made that method public because I wanted it to be exposed without exposing the protocol itself. That visibility mixing shouldn't have been allowed, and in release builds, the method wasn't visible.

Are you doing a debug or release build? Is this something that worked before but stopped working with a newer release, or is this the first time you're trying it? Any additional information would be helpful.
