### ISSUE TITLE
Missing copyright infos in license file

### ISSUE THREAD

**Issue by PaulForstner** [apple/swift-protobuf#1071] opened 2020-09-14 12:53 UTC
Hello, we want to ship an app with swift-protobuf and want to add the copyright notice on our license list, but we couldn't find it in the LICENSE.txt file. Would be much appreciated if you could add them in the line 189.

**Comment by tbkka** [comment] 2020-09-14 15:31
Thanks.  I'll get back to you on this.

**Comment by revolter** [comment] 2021-02-16 09:27
@PaulForstner, It's not actually missing; this is the intended behavior. See https://github.com/firebase/firebase-ios-sdk/issues/7105 for more details.

**Comment by thomasvl** [comment] 2022-09-09 16:18
@tbkka were you able to get an official reply for this so we can close it out?

**Comment by tbkka** [comment] 2024-03-04 22:40
As @revolter pointed out, this is a misunderstanding of that file.  The individual source code files have the correct attribution:  "Copyright Apple, Inc. and the project authors"

**Closed** 2024-03-04 22:40 UTC
