### ISSUE TITLE
Generate as class

### ISSUE THREAD

**Issue by j70** [apple/swift-protobuf#609] opened 2017-07-05 07:10 UTC
Provide an option to select whether to generate **Message** types as classes or structs, as of now everything is generated as structs. In some situations there may be a need to use the swift's nature of passing the class instances as references.

**Comment by thomasvl** [comment] 2017-07-05 13:58
Duplicate of #194 

See the other issues.  This would be a non trivial thing to support as it would take completely different generation as well as different runtime support.

**Closed by thomasvl** 2017-07-05 13:58 UTC

**Comment by tbkka** [comment] 2017-07-05 16:14
If you need class objects in order to interoperate with Obj-C frameworks, you might consider using Google's Obj-C implementation of protobuf.
