### ISSUE TITLE
Support looking up enum values by string

### ISSUE THREAD

**Issue by bruwozniak** [apple/swift-protobuf#948] opened 2020-02-06 11:41 UTC
It would be handy in some cases to be able to assign enum fields with values matching some string. In fact, this functionality already exists, but it is internal to the package and so can't be accessed when using the generated code.
See: https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/NameMap.swift#L271

There's already a TODO comment about this, see:
https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/NameMap.swift#L11

Right now the only way I've found to do it, is `MyMessage(textFormatString: "category: \(categoryString)").category` which is clearly sub-optimal.

**Comment by thomasvl** [comment] 2020-02-06 14:26
I believe this is a duplicate of #326.

Going the other way is #731.

**Closed by thomasvl** 2020-02-06 14:26 UTC
