### ISSUE TITLE
SwiftProtobuf as Xcode Sub Project Producing Errors

### ISSUE THREAD

**Issue by perlmunger** [apple/swift-protobuf#305] opened 2017-02-23 00:24 UTC
I've added the SwiftProtobuf.xcodproj file to my Xcode project and then added the protoc generated file to the project. I set the SwiftProtobuf project as a target dependency in the build phases. I've then added SwiftProtobuf.framework as an embedded binary (General tab for the target). It seems that Xcode is finding the framework okay, however, I am getting hundreds of errors stating "No type named '`typename`' in module 'SwiftProtobuf'" where `typename` is one of many types used in my protoc generated swift file.

<img width="469" alt="notypenamed" src="https://cloud.githubusercontent.com/assets/17556/23238813/0a926d66-f921-11e6-9d11-6e91b333240b.png">

Any idea why it's unable to find those? I can even command click the types that are supposedly missing and Xcode will take me right to the definition in the SwiftProtobuf project.

<img width="733" alt="eyerep_pb_swift" src="https://cloud.githubusercontent.com/assets/17556/23238941/b876dbd8-f921-11e6-8455-7a27f9e32393.png">

Thanks.

**Comment by tbkka** [comment] 2017-02-23 03:27
Have you upgraded Xcode or the Swift toolchain recently?  If so, you'll need to do a clean rebuild of your project and the Swift Protobuf framework to make sure everything is consistent.

**Comment by perlmunger** [comment] 2017-02-23 22:19
Thanks for the response, @tbkka. I haven't upgraded any development tools lately. Nevertheless, I did a clean clone of my repo (which defines SwiftProtobuf as a git submodule) into a new directory. I clone the submodules and then compile in Xcode (v8.2.1 btw) and I get the same errors. Any other ideas?

**Comment by thomasvl** [comment] 2017-02-23 22:22
What version is you submodule pulling in and what version of the plugin did you use to generate your sources?  This sounds like you might be using a current version of the plugin, but you module is pointing to an older version that doesn't match.

**Comment by perlmunger** [comment] 2017-02-23 23:55
@thomasvl Thanks for your help. I guess I'm not sure what you mean by which version. I made sure the submodule is using the master branch. I went into the submodule directory directly and did a `git pull origin master`. I then rebuilt the plugin and regenerated my swift code with `protoc --swift_out=. eyerep.proto` and overwrote the file in the project with the new one. Still getting the same errors.

**Comment by perlmunger** [comment] 2017-02-23 23:56
Interestingly I am able to add the project as a sub project to a new Xcode project and everything works just fine. I must have some environment issue I'm not seeing in my main project.

**Comment by thomasvl** [comment] 2017-02-24 21:10
Does that mean the issue is on your end and not in the project from here?

**Comment by perlmunger** [comment] 2017-02-25 03:57
@thomasvl I don't think I can be sure of that either way at the moment, however, I can close this and re-open it if I can determine it isn't just on my side. Thanks.

**Comment by perlmunger** [comment] 2017-03-02 22:33
I'm going to re-open this simply because I'm desperate and hoping someone could suggest something. I can't figure out what would cause the build to get all the way through and then at the very end just spit out hundreds of errors that seem like red-herrings. I did a pull from master again today and rebuilt `protoc-gen-swift` and placed it in my path over the old one. I then regenerated from my `.proto` file and replaced the previous generated Swift file with the new. I then did a `Clean Build Folder...` in Xcode and then built again. Still the same problem--just with the new names:

<img width="466" alt="eyerep_pb_swift" src="https://cloud.githubusercontent.com/assets/17556/23530027/2c677430-ff5d-11e6-8693-bc9be906b5e8.png">

Any thoughts at all?

**Comment by Meonardo** [comment] 2017-05-04 12:51
@perlmunger try upgrade SwiftProtoBuf to the latest one(I m using 0.9.901 currently).
 I don't add it to my project as submodule but I did check out by using the Swift Package Manager`dependencies: [
        .Package(url: "https://github.com/apple/swift-protobuf.git", Version(0,9,901))
    ]` on my macOS application, than I just drag the "swift-protobuf" to my project CLEAN & BUILD everything worked just fine.

**Comment by mathewa6** [comment] 2018-06-23 21:13
This is an old issue, but since it's still open and just in case someone else is having the same problem, please **make sure SwiftProtobuf.framework is code signed before using it on-device**. 

If it isn't the exact same issue is encountered.

**Comment by Loris94** [comment] 2019-06-29 13:50
@mathewa6 I'm having a problem similar to this (https://github.com/apple/swift-protobuf/issues/888).
I'm new to xcode and code signing is still black magic for me, how can I check that SwiftProtobuf.framework is code signed? It shouldn't be my issue but I want to give it a try.

**Comment by thomasvl** [comment] 2019-09-26 16:56
This hasn't gotten any updates in a while, and the original issue seems to have been specific to one project that wasn't able to be recreated in another project, so closing this out again.

**Closed by thomasvl** 2019-09-26 16:56 UTC
