### ISSUE TITLE
custom option not supported?

### ISSUE THREAD

**Issue by chen0572054** [apple/swift-protobuf#1108] opened 2021-02-01 19:46 UTC
Before opening a new issue, please double check the past issues (both open and
closed ones) to see if your problem has been discussed before and already
contains an answer/solution. Likewise, check the FAQ in the Documentation folder
for some common things -
  https://github.com/apple/swift-protobuf/blob/master/Documentation/FAQ.md

I am trying to add a custom option on message level. I followed the doc at https://developers.google.com/protocol-buffers/docs/proto#customoptions 
But found that BinaryDecoder has `extensions` to be nil in `decodeMessage` method of `Google_Protobuf_MessageOptions`. So, I cannot read the custom option value. But I do see it in the debug description.
Is it not supported right now or am I missing anything? Thank you!

Please be sure to include:

* what OS you are developing on (Linux or macOS, including the version)
macOS

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)
Xcode 12.3
Build version 12C33

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
1.14.0

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.
N/A
* lastly, if it all possible, provide a snippet of `.proto` and/or source
  that shows the problem.

```proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
    string some_option = 10001;
}

message AWEUserModel {
    string some_string_field = 1;
    option (some_option) = "Hello_World!";
}
```

Thank you!

**Comment by thomasvl** [comment] 2021-02-01 19:49
Duplicate of #761

**Closed by thomasvl** 2021-02-01 19:49 UTC
