### ISSUE TITLE
In case multiple modules, using mapping, adds module prefix to the imported type

### ISSUE THREAD

**Issue by mark2b** [apple/swift-protobuf#1112] opened 2021-02-21 14:21 UTC
protoc-gen-swift 1.15.0
macOS 11.2.1

In case multiple modules, using mapping, adds module prefix to the imported type

### mapping.txt
```
mapping {
  module_name: "ModuleA"
  proto_file_path: "A.proto"
}
mapping {
  module_name: "ModuleB"
  proto_file_path: "B.proto"
}
```

### A.proto
```
syntax = "proto3";
package PackageA;

message TypeA {
    int64 timestamp = 1;
}

```
### B.proto
```
syntax = "proto3";
package PackageB;

import "A.proto";

message TypeB {
    PackageA.TypeA someField = 1;
}

```

### B.pb.swift - generated ModuleB

Adds import ModuleA - **correct**
```
import ModuleA
```

Adds module prefix to the imported type - **not correct**
```
public var someField: ModuleA.PackageA_TypeA {
```

[sources.zip](https://github.com/apple/swift-protobuf/files/6017879/sources.zip)

**Comment by thomasvl** [comment] 2021-02-22 14:59
What makes this incorrect?  While the module name does't have to be repeated, it is the only way to ensure there is never a collision.  Since we have to mangle the proto package into the type names, it is possible two files could end up with collisions and the module name is needed to disambiguate.  So we always add the other module name to ensure there aren't any collisions.

**Comment by mark2b** [comment] 2021-02-22 16:14
I have compilation error 'PackageA_TypeA' is not a member type of 'ModuleA. 
Probably because I have public class ModuleA in the ModuleA

**Comment by thomasvl** [comment] 2021-02-22 16:21
Ah, that's not in your example.  I want to say there are some past discussions on the Swift Forums about problems like that and lack of good ways to disambiguate them, you might want to check those.  While we might be able to make the code a lot smart about trying to guess when the scoping is needed, when you have a collision like you have, it sounds like there will always be cases we might not be able to disambiguate.

**Comment by mark2b** [comment] 2021-02-22 21:25
May be prefixed module name can be optional controlled by parameter like fully_qualified_type:true
```
mapping {
  module_name: "ModuleA"
  proto_file_path: "A.proto"
  fully_qualified_type: true
}
```

**Comment by thomasvl** [comment] 2021-02-23 14:27
I'm not sure that helps.  We'd have to pick a default, and there will always be cases that fail no matter which we pick, and there is still the problem you hit of collisions between a local type and a module name.

**Comment by mark2b** [comment] 2021-02-23 14:36
There are many swift frameworks that have same Module & Type name, just because it is marketing name and can not be changed.
Do you have solution to solve this collision? Currently I edit generated file.
Using parameter as **fully_qualified_type** developer can turn it off in case of collision. But default is true - means current approach.

**Comment by thomasvl** [comment] 2021-02-23 15:23
For anyone else that also looks at this issue, https://forums.swift.org/t/pitch-fully-qualified-name-syntax/28482 seems to be the most recent discussion on the topic.  Nothing has been added to Swift yet to help deal with this.

I haven't thought about the extra file for aliasing that they mention to see if there is a way for the generator to attempt to avoid it (extra files during generation are generally problematic since build systems have trouble knowing about them). So it likely would come back to some more fields in the module mapping file if the generator can't be made smart enough to try and avoid the common cases.

**Comment by thomasvl** [comment] 2024-01-18 17:05
Closing this as the problem is specific to type collisions between modules and local types within a module, and that's something Swift generally needs a way to handle.  Simple removing the module name from the generated type references might solve this specific case, but it would fail if two modules provides a type as that case would now become ambiguous (the case we specifically adding the qualifications for).

**Closed by thomasvl** 2024-01-18 17:05 UTC
