### ISSUE TITLE
protoc-gen-swift cannot load SwiftProtobuf library when using SwiftProtobufPlugin in release mode

### ISSUE THREAD

**Issue by MikeWalrus** [apple/swift-protobuf#1506] opened 2023-11-19 14:09 UTC
The plugin works without issue when the build scheme is set to debug mode, but when doing a release build, protoc cannot find SwiftProtobuf when loading protoc-gen-swift:
```
dyld[57698]: Library not loaded: @rpath/SwiftProtobuf.framework/Versions/A/SwiftProtobuf

```

The log shows that in debug mode, protoc-gen-swift is compiled with
```
cd /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/SourcePackages/checkouts/swift-protobuf
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-macos10.13 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -O0 -w -L/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -L/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Debug -L/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Debug/PackageFrameworks -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Debug/PackageFrameworks -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Debug -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -iframework /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Debug/protoc-gen-swift.build/Objects-normal/arm64/protoc-gen-swift.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Debug/PackageFrameworks -Xlinker -object_path_lto -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Debug/protoc-gen-swift.build/Objects-normal/arm64/protoc-gen-swift_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Debug/protoc-gen-swift.build/Objects-normal/arm64/protoc_gen_swift.swiftmodule -Wl,-no_warn_duplicate_libraries -Wl,-no_warn_duplicate_libraries -framework SwiftProtobuf -framework SwiftProtobufPluginLibrary -Xlinker -dependency_info -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Debug/protoc-gen-swift.build/Objects-normal/arm64/protoc-gen-swift_dependency_info.dat -o /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Debug/protoc-gen-swift
```

But in release mode, it misses the rpath argument:
```
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-macos10.13 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -Os -w -L/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/EagerLinkingTBDs/Release -L/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Release -L/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/EagerLinkingTBDs/Release -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Release/PackageFrameworks -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Release/PackageFrameworks -F/Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Products/Release -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -iframework /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Release/protoc-gen-swift.build/Objects-normal/arm64/protoc-gen-swift.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -object_path_lto -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Release/protoc-gen-swift.build/Objects-normal/arm64/protoc-gen-swift_lto.o -Xlinker -debug_variant -fobjc-link-runtime -fprofile-instr-generate -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Release/protoc-gen-swift.build/Objects-normal/arm64/protoc_gen_swift.swiftmodule -Wl,-no_warn_duplicate_libraries -Wl,-no_warn_duplicate_libraries -framework SwiftProtobuf -framework SwiftProtobufPluginLibrary -Xlinker -dependency_info -Xlinker /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Release/protoc-gen-swift.build/Objects-normal/arm64/protoc-gen-swift_dependency_info.dat -o /Users/test/Library/Developer/Xcode/DerivedData/PaperPilot-cyqhgfgkjjzzwchgmxwnwngxtkbw/Build/Intermediates.noindex/SwiftProtobuf.build/Release/protoc-gen-swift.build/Objects-normal/arm64/Binary/protoc-gen-swift
```

I can reproduce this on Xcode 15.0 and 15.1 beta, with swift-protobuf 1.25.1.

**Comment by thomasvl** [comment] 2023-11-20 13:57
Since we haven't gotten any other reports, I'm guessing this is something unique to your set up?  Can you provide more detailed information about you builds?  Given the snippets you included, it doesn't sound like you are using SwiftPM to build the plugin?  What are the exact steps you are using?  Then someone might have some ideas.

**Comment by MikeWalrus** [comment] 2023-11-20 14:09
I'm just using the spm-plugin in Xcode following the instructions outlined in `Sources/protoc-gen-swift/Docs.docc/spm-plugin.md`.

**Comment by FranzBusch** [comment] 2023-11-22 14:01
This sounds like an SPM/Xcode problem. Would you mind filing a feedback using the [feedback assistant](https://feedbackassistant.apple.com/welcome) and share the feedback number with me. I don't think there is anything that `SwiftProtobuf` can do here.

**Comment by LSX-s-Software** [comment] 2023-11-23 02:33
I'm a collaborator with MikeWalrus. I have submitted the feedback `FB13402398`.

**Comment by FranzBusch** [comment] 2023-11-28 11:29
It looks like you are building SwiftProtobuf into an a framework. I assume this is where this problem comes from. Make sure to attach a reproducer Xcode project to your feedback.

**Comment by Lutzifer** [comment] 2023-12-12 09:09
I'm running into the very same problem, it doesn't seem to be that unique.

**Comment by thomasvl** [comment] 2024-01-18 17:02
Closing this since it seems the issues here are with Xcode's SwiftPM support and nothing we can do on this project.

**Closed by thomasvl** 2024-01-18 17:02 UTC

**Comment by Lutzifer** [comment] 2024-01-18 20:17
For me this disappeared after reducing the dependencies inside the project to a minimum, i.e. avoiding to depend on Protobuf (or GRPC) multiple times

**Comment by Lutzifer** [comment] 2024-10-24 12:15
I can confirm that this issue still exists and my solution for it still works (came here as I had the issue on another project)

**Comment by ethanndickson** [comment] 2025-03-10 04:39
> For me this disappeared after reducing the dependencies inside the project to a minimum, i.e. avoiding to depend on Protobuf (or GRPC) multiple times
Very helpful. Thank you
